# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
  #  depends_on:
  #    db:
  #     condition: service_healthy
  # db:
  #   image: mcr.microsoft.com/mssql/server
  #   restart: always
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_SA_PASSWORD=password
  #   ports:
  #     - "1433:1433"
  #   healthcheck:
  #     test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "password", "-Q", "SELECT 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
#volumes:
#  db-data:

